apiVersion: v1
kind: ServiceAccount
metadata:
  name: xstatefulset-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: xstatefulset-controller-manager
    {{- include "xstatefulset.labels" . | nindent 4 }}
