{{- if and .Values.webhook.enabled (eq .Values.global.certManagementMode "cert-manager") }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: xstatefulset-controller-manager-webhook-issuer
  namespace: {{ .Release.Namespace }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: xstatefulset-controller-manager-webhook-cert
  namespace: {{ .Release.Namespace }}
spec:
  dnsNames:
    - {{ .Values.webhook.serviceName }}.{{ .Release.Namespace }}.svc
    - {{ .Values.webhook.serviceName }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: xstatefulset-controller-manager-webhook-issuer
  secretName: {{ .Values.webhook.tls.certSecretName }}
{{- end }}
