{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: xstatefulset-mutating-webhook
  labels:
    app.kubernetes.io/component: xstatefulset-controller-manager
    {{- include "xstatefulset.labels" . | nindent 4 }}
  {{- if eq .Values.global.certManagementMode "cert-manager" }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/xstatefulset-webhook-cert
  {{- end }}
webhooks:
  - name: mxstatefulset.kb.io
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: {{ .Values.webhook.serviceName | default "xstatefulset-controller-manager-webhook" }}
        namespace: {{ .Release.Namespace }}
        path: /mutate-apps-x-k8s-io-v1-xstatefulset
        port: 443
      {{- if eq .Values.global.certManagementMode "manual" }}
      caBundle: {{ required "A caBundle is required when certManagementMode is 'manual'" .Values.global.webhook.caBundle | quote }}
      {{- end }}
    failurePolicy: {{ .Values.webhook.failurePolicy | default "Fail" }}
    matchPolicy: Equivalent
    namespaceSelector:
      {{- toYaml .Values.webhook.namespaceSelector | nindent 6 }}
    objectSelector:
      {{- toYaml .Values.webhook.objectSelector | nindent 6 }}
    rules:
      - apiGroups:
          - apps.x-k8s.io
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - xstatefulsets
        scope: "*"
    sideEffects: None
    timeoutSeconds: {{ .Values.webhook.timeoutSeconds | default 30 }}
{{- end }}
