{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.webhook.serviceName | default "xstatefulset-controller-manager-webhook" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "xstatefulset.labels" . | nindent 4 }}
    app.kubernetes.io/component: xstatefulset-controller-manager
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  selector:
    {{- include "xstatefulset.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: xstatefulset-controller-manager
{{- end }}
